
    create sequence revinfo_SEQ start with 1 increment by 50;

    create table app_connectors (
        cohort_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        trigger_source_connector_id bigint,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        description text,
        name varchar(255) not null unique,
        trigger_type varchar(255) check ((trigger_type in ('ON_CONNECTOR_SUCCESS'))),
        input_config jsonb,
        merge_config jsonb,
        pivot_config jsonb,
        schedule_settings jsonb,
        schema_mapping jsonb,
        upload_info jsonb,
        primary key (id)
    );

    create table cohort (
        approval_date date,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        description varchar(2048),
        cite_as text,
        copyright text,
        copyright_label varchar(255),
        keycloak_id varchar(255) not null,
        name varchar(255) not null unique,
        purpose text,
        status varchar(255) check ((status in ('DRAFT','ACTIVE','RETIRED','UNKNOWN'))),
        primary key (id)
    );

    create table cohort_audit (
        approval_date date,
        rev integer not null,
        revtype smallint,
        id bigint not null,
        description varchar(2048),
        cite_as text,
        copyright text,
        copyright_label varchar(255),
        name varchar(255),
        purpose text,
        status varchar(255) check ((status in ('DRAFT','ACTIVE','RETIRED','UNKNOWN'))),
        primary key (rev, id)
    );

    create table cohort_criteria (
        cohort_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        data_type_id varchar(255),
        description text,
        ontology_id varchar(255),
        type varchar(255) check ((type in ('INCLUSION','EXCLUSION'))),
        variable_role varchar(255) check ((variable_role in ('POPULATION','EXPOSURE','OUTCOME','COVARIATE'))),
        operator jsonb,
        primary key (id)
    );

    create table cohort_criteria_audit (
        rev integer not null,
        revtype smallint,
        cohort_id bigint,
        id bigint not null,
        data_type_id varchar(255),
        description text,
        ontology_id varchar(255),
        type varchar(255) check ((type in ('INCLUSION','EXCLUSION'))),
        variable_role varchar(255) check ((variable_role in ('POPULATION','EXPOSURE','OUTCOME','COVARIATE'))),
        operator jsonb,
        primary key (rev, id)
    );

    create table cohort_members (
        cohort_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        keycloak_id varchar(255) not null,
        type varchar(255) check ((type in ('MAINTAINER'))),
        primary key (id)
    );

    create table cohort_members_audit (
        rev integer not null,
        revtype smallint,
        cohort_id bigint,
        id bigint not null,
        type varchar(255) check ((type in ('MAINTAINER'))),
        primary key (rev, id)
    );

    create table cohort_queryability (
        cohort_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        schema_node_id bigint not null,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        queryability_info varchar(12) not null check ((queryability_info in ('VALUE','EXISTENCE','NONE'))),
        primary key (id),
        unique (cohort_id, schema_node_id)
    );

    create table cohort_queryability_audit (
        rev integer not null,
        revtype smallint,
        cohort_id bigint,
        id bigint not null,
        schema_node_id bigint,
        queryability_info varchar(12) check ((queryability_info in ('VALUE','EXISTENCE','NONE'))),
        primary key (rev, id)
    );

    create table connector_files (
        is_support_file boolean,
        cohort_id bigint,
        connector_id bigint,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        lo_oid bigint,
        size bigint,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        secret varchar(32),
        transformed_statistics_cache_key varchar(64),
        contentType varchar(255),
        fileName varchar(255),
        keycloak_id varchar(255) not null,
        preview_data jsonb,
        transformed_statistics jsonb,
        upload_info jsonb,
        upload_settings jsonb,
        primary key (id)
    );

    create table connector_preview_transformation_cache (
        row_count integer,
        step_index integer not null,
        connector_id bigint not null,
        connector_transformer_id bigint,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        fingerprint varchar(128) not null,
        columns_data jsonb,
        rows_data jsonb,
        primary key (id),
        constraint uc_preview_cache_connector_step unique (connector_id, step_index)
    );

    create table connector_run (
        delete_existing_patients boolean,
        dry_run boolean,
        cohort_id bigint not null,
        connector_id bigint not null,
        created_at timestamp(6) not null,
        current_element_nr bigint,
        current_row_nr bigint,
        current_transforming_step bigint,
        deleted_entities bigint,
        expected_elements bigint,
        failed_data_entries bigint,
        failed_entities bigint,
        id bigint generated by default as identity,
        new_data_entries bigint,
        new_entities bigint,
        processed_entities bigint,
        progess bigint not null,
        progress_extracting bigint,
        received_entities bigint,
        unchanged_entities bigint,
        updated_at timestamp(6) not null,
        updated_entities bigint,
        version bigint default 0 not null,
        error_message varchar(2000),
        current_step varchar(255) check ((current_step in ('INIT','EXTRACTING','TRANSFORMING','MAPPING','LOADING','FINISHED'))),
        keycloak_id varchar(255) not null,
        status varchar(255) not null check ((status in ('INIT','RUNNING','FINISHED','ERROR'))),
        primary key (id)
    );

    create table connector_run_error_logs (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        run_id bigint,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        level varchar(20),
        log_type varchar(20) check ((log_type in ('EXTRACTING','TRANSFORM','MAPPING','LOADING'))),
        field varchar(255),
        message text,
        patient_id varchar(255),
        primary key (id)
    );

    create table connector_run_step_messages (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        run_id bigint,
        run_step_id bigint,
        run_transformer_id bigint,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        message TEXT,
        process varchar(255),
        severity varchar(255) check ((severity in ('DEBUG','INFO','WARNING','ERROR','CRITICAL'))),
        type varchar(255) check ((type in ('METRIC','LOG'))),
        primary key (id)
    );

    create table connector_run_steps (
        progress float4,
        connector_run_id bigint,
        connector_transformation_id bigint,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        last_error varchar(2000),
        container_id varchar(255),
        status varchar(255) check ((status in ('PENDING','INITIALIZED','STARTED','RUNNING','FINISHED','STOPPED','ERROR'))),
        hyper_params jsonb,
        input_paths jsonb,
        primary key (id)
    );

    create table connector_transformers (
        app_version_id integer,
        position integer not null,
        connector_id bigint,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        app_image varchar(1000),
        column_name varchar(255),
        method_name varchar(255) not null,
        module varchar(255) not null,
        hyperparams jsonb,
        input_mapping jsonb,
        return_mapping jsonb,
        primary key (id)
    );

    create table custom_statistic (
        sort_order integer not null,
        created_at timestamp(6) not null,
        dashboard_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        type varchar(32) not null check ((type in ('BAR','PIE','LINE','SCATTER','HISTOGRAM','BOXPLOT','HEATMAP'))),
        name varchar(120) not null,
        config jsonb not null,
        primary key (id)
    );

    create table custom_statistics_dashboard (
        sort_order integer not null,
        cohort_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        name varchar(120) not null,
        primary key (id)
    );

    create table datatype (
        allow_null_values boolean default true,
        is_required boolean,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        type varchar(50) not null check ((type in ('INT','FLOAT','BOOLEAN','STRING','FILE','DATE','DATE_TIME','CATEGORICAL'))),
        description text,
        global_id varchar(255) not null unique,
        name varchar(255) not null,
        allowed_values json,
        mapping json,
        options json,
        validations json,
        primary key (id)
    );

    create table datatype_audit (
        allow_null_values boolean,
        is_required boolean,
        rev integer not null,
        revtype smallint,
        id bigint not null,
        type varchar(50) check ((type in ('INT','FLOAT','BOOLEAN','STRING','FILE','DATE','DATE_TIME','CATEGORICAL'))),
        description text,
        global_id varchar(255),
        name varchar(255),
        allowed_values json,
        mapping json,
        options json,
        validations json,
        primary key (rev, id)
    );

    create table federated_learning_experiments (
        created_at timestamp(6) not null,
        current_step_id bigint,
        finished_at timestamp(6),
        id bigint generated by default as identity,
        project_id bigint not null unique,
        started_at timestamp(6),
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        experiment_status varchar(255) check ((experiment_status in ('INIT','READY','PREPARE','RUNNING','SHUTDOWN','STOPPED','ERROR','FINISHED'))),
        unique_random_clinic_id varchar(255),
        primary key (id)
    );

    create table federated_learning_experiments_steps (
        progress float4,
        created_at timestamp(6) not null,
        experiment_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        workflow_node_id bigint not null,
        last_error varchar(2000),
        container_id varchar(255),
        step_status varchar(255) check ((step_status in ('PENDING','INITIALIZED','STARTED','RUNNING','FINISHED','STOPPED','ERROR'))),
        meta jsonb,
        relay_info jsonb,
        primary key (id)
    );

    create table federated_learning_experiments_steps_data (
        created_at timestamp(6) not null,
        file_id bigint,
        id bigint generated by default as identity,
        step_input_id bigint,
        step_output_id bigint,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        name varchar(255),
        result TEXT,
        primary key (id)
    );

    create table federated_learning_experiments_steps_messages (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        step_id bigint not null,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        message TEXT,
        process varchar(255),
        type varchar(255) check ((type in ('METRIC','LOG'))),
        primary key (id)
    );

    create table federated_learning_project (
        certificationLevel integer default 0 not null,
        coordinator_has_data boolean default true,
        is_coordinator boolean default false,
        platform_is_coordinator boolean default false,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        query_id bigint,
        request_id bigint not null unique,
        updated_at timestamp(6) not null,
        verified_on timestamp(6),
        version bigint default 0 not null,
        workflow_id bigint,
        description varchar(1000),
        name varchar(255),
        export_config json,
        primary key (id)
    );

    create table federated_learning_request (
        model_can_be_public boolean default false,
        model_need_to_be_public boolean default false,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        status varchar(20) not null check ((status in ('PENDING','APPROVED','RUNNING','REJECTED','COMPLETED','STOPPED'))),
        channel_id varchar(64),
        description TEXT,
        global_request_id varchar(255) not null,
        name varchar(255) not null,
        platform_user_id varchar(255) not null,
        primary key (id)
    );

    create table federated_learning_request_cohort (
        cohort_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        request_id bigint not null,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        status varchar(20) not null check ((status in ('PENDING','APPROVED','REJECTED'))),
        primary key (id),
        unique (request_id, cohort_id)
    );

    create table files (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        lo_oid bigint,
        size bigint,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        secret varchar(32),
        contentType varchar(255),
        fileName varchar(255),
        keycloak_id varchar(255) not null,
        primary key (id)
    );

    create table meta_patient_data_entry (
        value_boolean boolean,
        value_date date,
        value_float float4,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        patient_data_entry_id bigint not null,
        updated_at timestamp(6) not null,
        value_date_time timestamp(6) with time zone,
        value_int bigint,
        value_type bigint not null,
        version bigint default 0 not null,
        value_lob varchar(255),
        value_string TEXT,
        primary key (id)
    );

    create table meta_patient_data_entry_audit (
        rev integer not null,
        revtype smallint,
        value_boolean boolean,
        value_date date,
        value_float float4,
        id bigint not null,
        patient_data_entry_id bigint,
        value_date_time timestamp(6) with time zone,
        value_int bigint,
        value_type bigint,
        value_lob varchar(255),
        value_string TEXT,
        primary key (rev, id)
    );

    create table notifications (
        deliveryAttemptCount integer,
        archivedAt timestamp(6),
        created_at timestamp(6) not null,
        deliveredAt timestamp(6),
        deliveredFailedAt timestamp(6),
        id bigint generated by default as identity,
        readAt timestamp(6),
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        message varchar(4000) not null,
        actionUrl varchar(255),
        deliveryErrorMessage varchar(255),
        priority varchar(255) not null check ((priority in ('LOW','NORMAL','HIGH','CRITICAL'))),
        recipientUserId varchar(255) not null,
        sourceEntityId varchar(255),
        sourceEntityType varchar(255),
        sourceService varchar(255),
        status varchar(255) not null check ((status in ('PENDING','DELIVERED','FAILED','READ','ARCHIVED'))),
        title varchar(255) not null,
        type varchar(255) not null check ((type in ('INFO','SUCCESS','WARNING','ERROR','ACTION_REQUIRED'))),
        primary key (id)
    );

    create table ontology (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        description TEXT,
        global_id varchar(255) not null unique,
        name TEXT not null,
        root_source TEXT,
        primary key (id)
    );

    create table ontology_audit (
        rev integer not null,
        revtype smallint,
        id bigint not null,
        description TEXT,
        global_id varchar(255),
        name TEXT,
        root_source TEXT,
        primary key (rev, id)
    );

    create table patient_data (
        is_null_value boolean,
        value_boolean boolean,
        value_date date,
        value_float float4,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        patient_id bigint not null,
        schema_node_id bigint not null,
        updated_at timestamp(6) not null,
        value_date_time timestamp(6) with time zone,
        value_int bigint,
        version bigint default 0 not null,
        visit_timestamp timestamp(6) with time zone,
        import_schema_group_id varchar(255),
        value_blob TEXT,
        value_string TEXT,
        visit_id varchar(255),
        visit_timestamp_format varchar(255),
        primary key (id)
    );

    create table patient_data_audit (
        is_null_value boolean,
        rev integer not null,
        revtype smallint,
        value_boolean boolean,
        value_date date,
        value_float float4,
        id bigint not null,
        patient_id bigint,
        schema_node_id bigint,
        value_date_time timestamp(6) with time zone,
        value_int bigint,
        visit_timestamp timestamp(6) with time zone,
        import_schema_group_id varchar(255),
        value_blob TEXT,
        value_string TEXT,
        visit_id varchar(255),
        visit_timestamp_format varchar(255),
        primary key (rev, id)
    );

    create table patient_learning (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        patient_id bigint not null,
        request_id bigint not null,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        primary key (id),
        unique (patient_id, request_id)
    );

    create table patient_meta (
        cohort_id bigint,
        created_at timestamp(6) not null,
        data_entries_version bigint default 0 not null,
        id bigint generated by default as identity,
        last_queried_at timestamp(6),
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        external_patient_id varchar(1024) not null,
        primary key (id),
        unique (external_patient_id, cohort_id)
    );

    create table patient_meta_audit (
        rev integer not null,
        revtype smallint,
        cohort_id bigint,
        data_entries_version bigint,
        id bigint not null,
        external_patient_id varchar(1024),
        primary key (rev, id)
    );

    create table patient_tool_run (
        progress float4,
        cohort_id bigint,
        created_at timestamp(6) not null,
        finished_at timestamp(6),
        global_app_version_id bigint,
        id bigint generated by default as identity,
        started_at timestamp(6),
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        last_error varchar(2000),
        app_name varchar(255),
        container_id varchar(255),
        error varchar(255),
        image varchar(255),
        run_status varchar(255) check ((run_status in ('PENDING','INITIALIZED','STARTED','RUNNING','FINISHED','STOPPED','ERROR'))),
        tool_type varchar(255) check ((tool_type in ('IMPORT','EXPORT','TRANSFORM'))),
        hyper_params json,
        primary key (id)
    );

    create table patient_tool_run_file (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        lo_oid bigint,
        run_id bigint not null,
        size bigint,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        secret varchar(32),
        contentType varchar(255),
        fileName varchar(255),
        keycloak_id varchar(255) not null,
        primary key (id)
    );

    create table patient_tool_run_log (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        run_id bigint not null,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        message TEXT,
        process varchar(255),
        type varchar(255) check ((type in ('METRIC','LOG'))),
        primary key (id)
    );

    create table permission (
        is_allowed_to_query boolean not null,
        query_retry_time integer,
        query_sample_threshold integer,
        valid_from date,
        valid_until date,
        cohort_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        auto_metrics_access varchar(255) check ((auto_metrics_access in ('ALL','NONE'))),
        auto_statistics_access varchar(255) check ((auto_statistics_access in ('ALL','NONE'))),
        auto_training_access varchar(255) check ((auto_training_access in ('ALL','NONE','CERTIFIED_APPS'))),
        user_id varchar(255),
        primary key (id)
    );

    create table permission_audit (
        is_allowed_to_query boolean,
        query_retry_time integer,
        query_sample_threshold integer,
        rev integer not null,
        revtype smallint,
        valid_from date,
        valid_until date,
        cohort_id bigint,
        id bigint not null,
        auto_metrics_access varchar(255) check ((auto_metrics_access in ('ALL','NONE'))),
        auto_statistics_access varchar(255) check ((auto_statistics_access in ('ALL','NONE'))),
        auto_training_access varchar(255) check ((auto_training_access in ('ALL','NONE','CERTIFIED_APPS'))),
        user_id varchar(255),
        primary key (rev, id)
    );

    create table queries (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        received_at timestamp(6),
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        global_unique_query_id varchar(255) not null unique,
        keycloak_id varchar(255),
        query_string TEXT not null,
        status varchar(255) not null check ((status in ('UNKNOWN','RECEIVED_EAM','REJECTED_EAM_PRE_HARMONIZED','RECEIVED_HARMONIZED','REJECTED_HARMONIZED','REJECTED_EAM_POST_HARMONIZED','COMPLETED'))),
        status_message TEXT,
        primary key (id)
    );

    create table query_patient (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        patient_id bigint not null,
        query_id bigint not null,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        primary key (id),
        unique (patient_id, query_id)
    );

    create table query_queried_cohorts (
        cohort_id bigint,
        query_id bigint not null,
        unique (query_id, cohort_id)
    );

    create table request_data_statistics (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        query_id bigint,
        updated_at timestamp(6) not null,
        verified_on timestamp(6),
        version bigint default 0 not null,
        request_id uuid,
        status varchar(20) not null check ((status in ('PENDING','APPROVED','RUNNING','REJECTED','COMPLETED','STOPPED'))),
        request_keycloak_id varchar(255) not null,
        verified_by_keycloak_id varchar(255),
        primary key (id)
    );

    create table request_run_metrics (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        project_id bigint not null,
        updated_at timestamp(6) not null,
        verified_on timestamp(6),
        version bigint default 0 not null,
        global_request_id uuid not null,
        status varchar(20) not null check ((status in ('PENDING','APPROVED','RUNNING','REJECTED','COMPLETED','STOPPED'))),
        request_keycloak_id varchar(255) not null,
        verified_by_keycloak_id varchar(255),
        primary key (id)
    );

    create table revinfo (
        id integer not null,
        connector_id bigint,
        run_id bigint,
        timestamp bigint not null,
        keycloak_id varchar(1024) not null,
        primary key (id)
    );

    create table schemanode (
        cohort_id bigint,
        created_at timestamp(6) not null,
        data_type_id bigint,
        depth bigint,
        id bigint generated by default as identity,
        ontology_id bigint,
        parent_id bigint,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        name varchar(1024) not null,
        created_by varchar(255),
        description text,
        global_id varchar(255) not null,
        type varchar(255) not null check ((type in ('ROOT','GROUP','ATOMIC_ATTRIBUTE','LIST_ATTRIBUTE'))),
        primary key (id)
    );

    create table schemanode_audit (
        rev integer not null,
        revtype smallint,
        cohort_id bigint,
        data_type_id bigint,
        depth bigint,
        id bigint not null,
        ontology_id bigint,
        parent_id bigint,
        name varchar(1024),
        created_by varchar(255),
        description text,
        global_id varchar(255),
        type varchar(255) check ((type in ('ROOT','GROUP','ATOMIC_ATTRIBUTE','LIST_ATTRIBUTE'))),
        primary key (rev, id)
    );

    create table workflow (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        publish_status varchar(50) check ((publish_status in ('PUBLISHED','UNPUBLISHED'))),
        description varchar(2000),
        keycloak_id varchar(255) not null,
        name varchar(255),
        export_config json,
        primary key (id)
    );

    create table workflow_connections (
        is_input_connection BOOLEAN DEFAULT FALSE not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        input_node_id bigint not null,
        output_node_id bigint,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        workflow_id bigint not null,
        input_config_name varchar(255) not null,
        input_file_name varchar(255),
        input_id varchar(255) not null,
        output_config_name varchar(255),
        output_file_name varchar(255),
        output_id varchar(255) not null,
        primary key (id)
    );

    create table workflow_node (
        execution_order integer,
        is_trainable boolean default false,
        old_fc_version boolean,
        supports_federated_learning boolean default false,
        created_at timestamp(6) not null,
        global_app_id bigint,
        global_app_version_id bigint,
        global_model_sub_id bigint,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        workflow_id bigint not null,
        hyperParams TEXT,
        imageName varchar(255),
        node_id varchar(255),
        position TEXT,
        primary key (id)
    );

    create index idx_app_connectors_cohort_id 
       on app_connectors (cohort_id);

    create index idx_cohort_criteria_cohort_id 
       on cohort_criteria (cohort_id);

    create index idx_cohort_members_cohort_id 
       on cohort_members (cohort_id);

    create index idx_cohort_queryability_schema_node_id 
       on cohort_queryability (schema_node_id);

    create index idx_connector_files_connector_id 
       on connector_files (connector_id);

    create index idx_connector_files_cohort_id 
       on connector_files (cohort_id);

    create index idx_preview_cache_connector_id 
       on connector_preview_transformation_cache (connector_id);

    create index idx_preview_cache_connector_step 
       on connector_preview_transformation_cache (connector_id, step_index);

    create index idx_connector_run_cohort_id 
       on connector_run (cohort_id);

    create index idx_connector_run_connector_id 
       on connector_run (connector_id);

    create index idx_connector_run_error_logs_run_id 
       on connector_run_error_logs (run_id);

    create index idx_connector_run_step_messages_run_step_id 
       on connector_run_step_messages (run_step_id);

    create index idx_connector_run_step_messages_run_transformer_id 
       on connector_run_step_messages (run_transformer_id);

    create index idx_connector_run_step_messages_run_id 
       on connector_run_step_messages (run_id);

    create index idx_connector_run_steps_connector_run_id 
       on connector_run_steps (connector_run_id);

    create index idx_connector_run_steps_connector_transformation_id 
       on connector_run_steps (connector_transformation_id);

    create index idx_connector_transformers_connector_id 
       on connector_transformers (connector_id);

    create index idx_custom_statistic_dashboard_id 
       on custom_statistic (dashboard_id);

    create index idx_custom_statistics_dashboard_cohort_id 
       on custom_statistics_dashboard (cohort_id);

    create index idx_federated_learning_experiments_project_id 
       on federated_learning_experiments (project_id);

    create index idx_federated_learning_experiments_steps_data_file_id 
       on federated_learning_experiments_steps_data (file_id);

    create index idx_federated_learning_experiments_steps_data_step_input_id 
       on federated_learning_experiments_steps_data (step_input_id);

    create index idx_federated_learning_experiments_steps_data_step_output_id 
       on federated_learning_experiments_steps_data (step_output_id);

    create index idx_federated_learning_experiments_steps_messages_step_id 
       on federated_learning_experiments_steps_messages (step_id);

    create index idx_federated_learning_project_query_id 
       on federated_learning_project (query_id);

    create index idx_federated_learning_project_workflow_id 
       on federated_learning_project (workflow_id);

    create index idx_federated_learning_project_request_id 
       on federated_learning_project (request_id);

    create index idx_fl_request_cohort_request_id 
       on federated_learning_request_cohort (request_id);

    create index idx_fl_request_cohort_cohort_id 
       on federated_learning_request_cohort (cohort_id);

    create index idx_meta_patient_data_entry_patient_data_entry_id 
       on meta_patient_data_entry (patient_data_entry_id);

    create index idx_patient_data_patient_id 
       on patient_data (patient_id);

    create index idx_patient_data_patient_id_id 
       on patient_data (patient_id, id);

    create index idx_patient_data_schema_node_id 
       on patient_data (schema_node_id);

    create index idx_patient_learning_request_id 
       on patient_learning (request_id);

    create index idx_patient_meta_cohort_id 
       on patient_meta (cohort_id);

    create index idx_patient_meta_cohort_id_id 
       on patient_meta (cohort_id, id);

    create index idx_patient_tool_run_cohort_id 
       on patient_tool_run (cohort_id);

    create index idx_patient_tool_run_file_run_id 
       on patient_tool_run_file (run_id);

    create index idx_patient_tool_run_log_run_id 
       on patient_tool_run_log (run_id);

    create index idx_permission_cohort_id 
       on permission (cohort_id);

    create index idx_query_patient_query_id 
       on query_patient (query_id);

    create index idx_query_queried_cohorts_query_id 
       on query_queried_cohorts (query_id);

    create index idx_query_queried_cohorts_cohort_id 
       on query_queried_cohorts (cohort_id);

    create index idx_request_data_statistics_query_id 
       on request_data_statistics (query_id);

    create index idx_request_run_metrics_project_id 
       on request_run_metrics (project_id);

    create index idx_revinfo_run_id_timestamp 
       on revinfo (run_id, timestamp);

    create index idx_revinfo_connector_id 
       on revinfo (connector_id);

    create index idx_schemanode_cohort_id 
       on schemanode (cohort_id);

    create index idx_schemanode_parent_id 
       on schemanode (parent_id);

    create index idx_schemanode_data_type_id 
       on schemanode (data_type_id);

    create index idx_schemanode_ontology_id 
       on schemanode (ontology_id);

    create index idx_schemanode_data_type_id_ontology_id 
       on schemanode (data_type_id, ontology_id);

    create index idx_workflow_connections_workflow_id 
       on workflow_connections (workflow_id);

    create index idx_workflow_connections_input_node_id 
       on workflow_connections (input_node_id);

    create index idx_workflow_connections_output_node_id 
       on workflow_connections (output_node_id);

    create index idx_workflow_node_workflow_id 
       on workflow_node (workflow_id);

    alter table if exists app_connectors 
       add constraint FKrc8hevvghi7otpa91w8iqyd30 
       foreign key (cohort_id) 
       references cohort;

    alter table if exists cohort_audit 
       add constraint FKphyws823nbpaxqtnu1si91hx1 
       foreign key (rev) 
       references revinfo;

    alter table if exists cohort_criteria 
       add constraint FKimejrxtipsnxujw1181saq0e1 
       foreign key (cohort_id) 
       references cohort;

    alter table if exists cohort_criteria_audit 
       add constraint FKeupjvqhou8fymas29thgdtdo1 
       foreign key (rev) 
       references revinfo;

    alter table if exists cohort_members 
       add constraint FK1kg2uakcpqgdxk5gjbby7eht0 
       foreign key (cohort_id) 
       references cohort 
       on delete cascade;

    alter table if exists cohort_members_audit 
       add constraint FKhktvgy73ic5wf73lfbq0cjmtf 
       foreign key (rev) 
       references revinfo;

    alter table if exists cohort_queryability 
       add constraint FKetf3iugrawer442d2ubpvbcpm 
       foreign key (cohort_id) 
       references cohort 
       on delete cascade;

    alter table if exists cohort_queryability 
       add constraint FKlyktgork4fklddpiybexx77tp 
       foreign key (schema_node_id) 
       references schemanode;

    alter table if exists cohort_queryability_audit 
       add constraint FKgt9g7wubq4husb6iwowihwk2y 
       foreign key (rev) 
       references revinfo;

    alter table if exists connector_files 
       add constraint FKkxfsfvp5ut55gereo611ae3hj 
       foreign key (cohort_id) 
       references cohort;

    alter table if exists connector_files 
       add constraint FK943c3m867kd2omnbg3e1niv9a 
       foreign key (connector_id) 
       references app_connectors 
       on delete cascade;

    alter table if exists connector_preview_transformation_cache 
       add constraint FK909r2a3ovecmectohljg7fh5p 
       foreign key (connector_id) 
       references app_connectors 
       on delete cascade;

    alter table if exists connector_preview_transformation_cache 
       add constraint FK92gsfyvxuq544qmd2e0un7c8i 
       foreign key (connector_transformer_id) 
       references connector_transformers 
       on delete cascade;

    alter table if exists connector_run 
       add constraint FKtn6oyly6x6yg0g6i5oj5lgxwi 
       foreign key (cohort_id) 
       references cohort;

    alter table if exists connector_run 
       add constraint FK7mx78s2j10aqqgj8cicvb2s6o 
       foreign key (connector_id) 
       references app_connectors 
       on delete cascade;

    alter table if exists connector_run_error_logs 
       add constraint FKbbmtd4eu4f1pmmvd8v0xfbulg 
       foreign key (run_id) 
       references connector_run 
       on delete cascade;

    alter table if exists connector_run_step_messages 
       add constraint FKbilpidqqyrdik4cqwudve6485 
       foreign key (run_id) 
       references connector_run 
       on delete cascade;

    alter table if exists connector_run_step_messages 
       add constraint FKdj98ifiobven3caywae1au6ec 
       foreign key (run_step_id) 
       references connector_run_steps 
       on delete cascade;

    alter table if exists connector_run_step_messages 
       add constraint FKp4jm0rj46lcktvdjl59gd9v2f 
       foreign key (run_transformer_id) 
       references connector_transformers;

    alter table if exists connector_run_steps 
       add constraint FK787xb1el0j9rgypdmf57jxl6w 
       foreign key (connector_run_id) 
       references connector_run 
       on delete cascade;

    alter table if exists connector_run_steps 
       add constraint FKkmqq26u8wj8y96l82ny00r879 
       foreign key (connector_transformation_id) 
       references connector_transformers;

    alter table if exists connector_transformers 
       add constraint FKsela6s24acq4d5o82cc1csx26 
       foreign key (connector_id) 
       references app_connectors 
       on delete cascade;

    alter table if exists custom_statistic 
       add constraint FK50qorp100komeligi6amsw6fl 
       foreign key (dashboard_id) 
       references custom_statistics_dashboard 
       on delete cascade;

    alter table if exists custom_statistics_dashboard 
       add constraint FK9oln823s5025957s2q51abmwp 
       foreign key (cohort_id) 
       references cohort 
       on delete cascade;

    alter table if exists datatype_audit 
       add constraint FKk3iw02v5auef616t4pbra14b4 
       foreign key (rev) 
       references revinfo;

    alter table if exists federated_learning_experiments 
       add constraint FKcmi5eoy9hbr8lg6w8kfbrgxcq 
       foreign key (current_step_id) 
       references federated_learning_experiments_steps;

    alter table if exists federated_learning_experiments 
       add constraint FKfvnlbh7liq1lv4hc909q8lclj 
       foreign key (project_id) 
       references federated_learning_project;

    alter table if exists federated_learning_experiments_steps 
       add constraint FKaasr4ys8dty05gvd4610tpkix 
       foreign key (experiment_id) 
       references federated_learning_experiments 
       on delete cascade;

    alter table if exists federated_learning_experiments_steps 
       add constraint FKhvy25lovsnkjk3crda8p2twmb 
       foreign key (workflow_node_id) 
       references workflow_node;

    alter table if exists federated_learning_experiments_steps_data 
       add constraint FKqh688cyjguh6i8xfxdhr7l3cv 
       foreign key (file_id) 
       references files;

    alter table if exists federated_learning_experiments_steps_data 
       add constraint FKny8ukakm48wo833gubdx61uaj 
       foreign key (step_input_id) 
       references federated_learning_experiments_steps;

    alter table if exists federated_learning_experiments_steps_data 
       add constraint FKaw01f15e54hpi0h3yl0es0f67 
       foreign key (step_output_id) 
       references federated_learning_experiments_steps;

    alter table if exists federated_learning_experiments_steps_messages 
       add constraint FK4nq5quxe3b13wicyblo1swqgr 
       foreign key (step_id) 
       references federated_learning_experiments_steps;

    alter table if exists federated_learning_project 
       add constraint FKiwn231apobnwqa6lnnvnksp4m 
       foreign key (query_id) 
       references queries;

    alter table if exists federated_learning_project 
       add constraint FK7ef8vyxhqs6b2g65em745o3hj 
       foreign key (request_id) 
       references federated_learning_request;

    alter table if exists federated_learning_project 
       add constraint FKi9rm28s43hpeq64abwn7luw09 
       foreign key (workflow_id) 
       references workflow;

    alter table if exists federated_learning_request_cohort 
       add constraint FKhp8bf77h5yekoerpiv8ef7jkr 
       foreign key (cohort_id) 
       references cohort;

    alter table if exists federated_learning_request_cohort 
       add constraint FKgw96l0i7fpivw4uvek4yqrj0q 
       foreign key (request_id) 
       references federated_learning_request;

    alter table if exists meta_patient_data_entry 
       add constraint FKjkbhnoley1t4l7xwdl32uyjyw 
       foreign key (patient_data_entry_id) 
       references patient_data;

    alter table if exists meta_patient_data_entry 
       add constraint FKk3kwqosbtjyjdi86s5c3aq982 
       foreign key (value_type) 
       references schemanode;

    alter table if exists meta_patient_data_entry_audit 
       add constraint FKrdy9fpqfvgpmg2reprxxf9pyj 
       foreign key (rev) 
       references revinfo;

    alter table if exists ontology_audit 
       add constraint FK47xrcffteab4lxo8qjne66mk3 
       foreign key (rev) 
       references revinfo;

    alter table if exists patient_data 
       add constraint FKmy6d5kj3fvdu3a9945uhqwvl7 
       foreign key (patient_id) 
       references patient_meta 
       on delete cascade;

    alter table if exists patient_data 
       add constraint FKpcs027ykn94wvis2b9uowulqx 
       foreign key (schema_node_id) 
       references schemanode 
       on delete cascade;

    alter table if exists patient_data_audit 
       add constraint FKdpxtc33289mnw4xabvlk24cx1 
       foreign key (rev) 
       references revinfo;

    alter table if exists patient_learning 
       add constraint FKjt9515uhl5cj0f25cqrw07vj7 
       foreign key (patient_id) 
       references patient_meta 
       on delete cascade;

    alter table if exists patient_learning 
       add constraint FKkgetrsuyw7mdjg5cawlv7n2ww 
       foreign key (request_id) 
       references federated_learning_request 
       on delete cascade;

    alter table if exists patient_meta 
       add constraint FKf11amjjb7brqdflhv3uidb9kc 
       foreign key (cohort_id) 
       references cohort 
       on delete cascade;

    alter table if exists patient_meta_audit 
       add constraint FK13lnboyd03yrc1lxwpc93uio0 
       foreign key (rev) 
       references revinfo;

    alter table if exists patient_tool_run 
       add constraint fk_patient_tool_run_cohort 
       foreign key (cohort_id) 
       references cohort;

    alter table if exists patient_tool_run_file 
       add constraint FKuels4a0o4xbsr99eigsj0xf5 
       foreign key (run_id) 
       references patient_tool_run;

    alter table if exists patient_tool_run_log 
       add constraint FKl1cg0q898ob99rpe9jocw06g 
       foreign key (run_id) 
       references patient_tool_run;

    alter table if exists permission 
       add constraint FKjvhng2u7968md0p3oyddqfnus 
       foreign key (cohort_id) 
       references cohort 
       on delete cascade;

    alter table if exists permission_audit 
       add constraint FKd3ewhivqnh013q5m18ff2vx75 
       foreign key (rev) 
       references revinfo;

    alter table if exists query_patient 
       add constraint FKcs8eu4502e3pks6yt245dsh8o 
       foreign key (patient_id) 
       references patient_meta 
       on delete cascade;

    alter table if exists query_patient 
       add constraint FKlcrvexit53s2yu44t9qdc82dr 
       foreign key (query_id) 
       references queries 
       on delete cascade;

    alter table if exists query_queried_cohorts 
       add constraint FKmonbsl436lqomd18ih675a9me 
       foreign key (query_id) 
       references queries;

    alter table if exists request_data_statistics 
       add constraint FKgyn3qph1grwnlc576r8a07f4v 
       foreign key (query_id) 
       references queries;

    alter table if exists request_run_metrics 
       add constraint FK91wsq2xth91hy1sss2j28tcqy 
       foreign key (project_id) 
       references federated_learning_project;

    alter table if exists schemanode 
       add constraint FK7p4vxw91jcnh904qe7umck5e0 
       foreign key (cohort_id) 
       references cohort;

    alter table if exists schemanode 
       add constraint FKrega011s1uukcasr4rph4jjh6 
       foreign key (data_type_id) 
       references datatype;

    alter table if exists schemanode 
       add constraint FKoc7rqi703wr6d4o7swtw6rxr3 
       foreign key (ontology_id) 
       references ontology;

    alter table if exists schemanode 
       add constraint FKed91lut4k9yxj2puimvw8y1lx 
       foreign key (parent_id) 
       references schemanode;

    alter table if exists schemanode_audit 
       add constraint FK860hnt7v2pc55bog8oib6maur 
       foreign key (rev) 
       references revinfo;

    alter table if exists workflow_connections 
       add constraint FKh7b9k39pyciip00x9iffhc96o 
       foreign key (input_node_id) 
       references workflow_node;

    alter table if exists workflow_connections 
       add constraint FK1chtq01ga3wsfmbwe8onsvdey 
       foreign key (output_node_id) 
       references workflow_node;

    alter table if exists workflow_connections 
       add constraint FK6epvfncscs6utns3dgdrphjxm 
       foreign key (workflow_id) 
       references workflow 
       on delete cascade;

    alter table if exists workflow_node 
       add constraint FKko4nyv15u7ixp39g9ah8tcpb8 
       foreign key (workflow_id) 
       references workflow 
       on delete cascade;
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

