
    create table data_analysis (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        keycloak_id varchar(255) not null,
        llmSummary TEXT,
        name TEXT,
        primary key (id)
    );

    create table data_analysis_chat_human_in_the_loop_request (
        is_answered boolean default false not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        message_id bigint not null,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        answer TEXT,
        request TEXT,
        tools jsonb,
        primary key (id)
    );

    create table data_analysis_chat_message (
        is_done boolean,
        is_request boolean,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        workflow_id bigint,
        error_message TEXT,
        message TEXT,
        status_message TEXT,
        action jsonb,
        reasonings jsonb,
        tools jsonb,
        primary key (id)
    );

    create table data_analysis_files (
        created_at timestamp(6) not null,
        data_analysis_id bigint not null,
        file_id bigint,
        id bigint generated by default as identity,
        prediction_id bigint,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        workflow_step_id bigint,
        input_name varchar(255),
        keycloak_id varchar(255) not null,
        output_name varchar(255),
        primary key (id)
    );

    create table data_analysis_predictions (
        app_version_id bigint,
        created_at timestamp(6) not null,
        data_analysis_id bigint,
        id bigint generated by default as identity,
        sub_model_id bigint,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        container_id varchar(255),
        hyper_params TEXT,
        inputs TEXT,
        keycloak_id varchar(255) not null,
        last_error TEXT,
        last_log TEXT,
        raw_logs TEXT,
        result TEXT,
        status varchar(255) check ((status in ('PENDING','INITIALIZED','STARTED','RUNNING','FINISHED','STOPPED','ERROR'))),
        meta jsonb,
        primary key (id)
    );

    create table data_analysis_workflow_run_step_messages (
        created_at timestamp(6) not null,
        experiment_step_id bigint,
        id bigint generated by default as identity,
        prediction_id bigint,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        message TEXT,
        process varchar(255),
        run_mode varchar(255) not null check ((run_mode in ('PREDICTION','WORKFLOW'))),
        type varchar(255) check ((type in ('METRIC','LOG'))),
        primary key (id)
    );

    create table data_analysis_workflow_run_steps (
        progress float4,
        created_at timestamp(6) not null,
        experiment_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        workflow_node_id bigint not null,
        last_error varchar(2000),
        container_id varchar(255),
        inputs TEXT,
        result TEXT,
        step_status varchar(255) check ((step_status in ('PENDING','INITIALIZED','STARTED','RUNNING','FINISHED','STOPPED','ERROR'))),
        meta jsonb,
        primary key (id)
    );

    create table data_analysis_workflow_runs (
        created_at timestamp(6) not null,
        current_step_id bigint,
        data_analysis_id bigint,
        finished_at timestamp(6),
        id bigint generated by default as identity,
        started_at timestamp(6),
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        workflow_id bigint,
        experiment_status varchar(255) check ((experiment_status in ('INIT','READY','PREPARE','RUNNING','SHUTDOWN','STOPPED','ERROR','FINISHED'))),
        keycloak_id varchar(255) not null,
        primary key (id)
    );

    create table data_statistics_result (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        query_id bigint not null,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        request_id uuid,
        random_clinic_id varchar(255),
        statistics jsonb,
        primary key (id)
    );

    create table experiments (
        created_at timestamp(6) not null,
        federated_app_version_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        description varchar(255),
        diagram_config TEXT,
        input TEXT,
        input_file_path varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table experiments_run_messages (
        created_at timestamp(6) not null,
        experiment_run_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        message TEXT,
        process varchar(255),
        type varchar(255) check ((type in ('METRIC','LOG'))),
        primary key (id)
    );

    create table experiments_runs (
        created_at timestamp(6) not null,
        experiment_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        color varchar(255),
        error TEXT,
        hyperParams TEXT,
        name varchar(255),
        output TEXT,
        status varchar(255) check ((status in ('PENDING','INITIALIZED','STARTED','RUNNING','FINISHED','STOPPED','ERROR'))),
        meta jsonb,
        primary key (id)
    );

    create table federated_app_authors (
        created_at timestamp(6) not null,
        federated_app_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        keycloak_id varchar(255) not null,
        primary key (id)
    );

    create table federated_app_hyperparam_configs (
        max_value float4,
        min_value float4,
        created_at timestamp(6) not null,
        federated_app_version_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        name varchar(50),
        defaultValue varchar(255),
        description varchar(255),
        mode varchar(255) check ((mode in ('TRAINING','PREDICTION','BOTH'))),
        options varchar(255),
        pattern varchar(255),
        type varchar(255) check ((type in ('STRING','INTEGER','FLOAT','BOOLEAN','CATEGORICAL'))),
        primary key (id)
    );

    create table federated_app_input_configs (
        has_header boolean,
        index_col integer,
        required boolean not null,
        created_at timestamp(6) not null,
        federated_app_version_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        name varchar(50),
        delimiter varchar(255),
        description varchar(255),
        max_value varchar(255),
        min_value varchar(255),
        mode varchar(255) check ((mode in ('TRAINING','PREDICTION','BOTH'))),
        shape varchar(255),
        type varchar(255) check ((type in ('HTML','CSV','TSV','JSON','IMAGE','TEXT','STRING','PATH','UNKNOWN'))),
        tabular_schema jsonb,
        primary key (id)
    );

    create table federated_app_output_configs (
        has_header boolean,
        index_col integer,
        created_at timestamp(6) not null,
        federated_app_version_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        name varchar(50),
        delimiter varchar(255),
        description varchar(255),
        max_value varchar(255),
        min_value varchar(255),
        mode varchar(255) check ((mode in ('TRAINING','PREDICTION','BOTH'))),
        shape varchar(255),
        type varchar(255) check ((type in ('HTML','CSV','TSV','JSON','IMAGE','TEXT','STRING','PATH','UNKNOWN'))),
        tabular_schema jsonb,
        primary key (id)
    );

    create table federated_app_tags (
        privacy boolean default false not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        name varchar(50) unique,
        primary key (id)
    );

    create table federated_app_versions (
        certification_level integer default 0,
        needs_host_access boolean default false,
        needs_internet_access boolean default false,
        created_at timestamp(6) not null,
        federated_app_id bigint not null,
        id bigint generated by default as identity,
        major_version bigint,
        minor_version bigint,
        patch_version bigint,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        publish_status varchar(50) check ((publish_status in ('PUBLISHED','UNPUBLISHED'))),
        publish_hash varchar(100) unique,
        short_description varchar(5000),
        long_description varchar(20000),
        changelog varchar(255),
        image_name varchar(255),
        publish_info json,
        primary key (id)
    );

    create table federated_apps (
        old_fc_version boolean,
        supports_federated_learning boolean default false not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        unique_app_id uuid not null unique,
        name varchar(100),
        source_url varchar(1000),
        icon varchar(255),
        slug varchar(255) unique,
        type varchar(255) check ((type in ('PRE_PROCESSING','ANALYSIS','POST_PROCESSING','EVALUATION','SELF_LEARNED','DATA_TRANSFORMATION','EXTRACTOR','EXPORT'))),
        primary key (id)
    );

    create table federated_apps_tags (
        federated_app_id bigint not null,
        federated_tag_id bigint not null,
        primary key (federated_app_id, federated_tag_id)
    );

    create table federated_participant_messages (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        participant_id bigint not null,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        message TEXT,
        process varchar(255),
        type varchar(255) check ((type in ('METRIC','LOG'))),
        primary key (id)
    );

    create table federated_round_messages (
        round_nr integer,
        created_at timestamp(6) not null,
        federated_run_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        communication_id varchar(255),
        direction varchar(255),
        from_participant varchar(255),
        payload_preview TEXT,
        to_participant varchar(255),
        primary key (id)
    );

    create table federated_run_participants (
        current_round integer,
        messages_received integer,
        messages_sent integer,
        created_at timestamp(6) not null,
        federated_run_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        participant_id varchar(255) not null,
        role varchar(255) check ((role in ('CLIENT','AGGREGATOR'))),
        status varchar(255) check ((status in ('PENDING','INITIALIZED','STARTED','RUNNING','FINISHED','STOPPED','ERROR'))),
        config jsonb,
        hyper_params jsonb,
        input_file_paths jsonb,
        waiting_for jsonb,
        primary key (id)
    );

    create table federated_test_runs (
        current_round integer,
        start_aggregator boolean,
        total_rounds integer,
        created_at timestamp(6) not null,
        federated_app_version_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        aggregator_id varchar(255),
        error TEXT,
        status varchar(255) check ((status in ('PENDING','INITIALIZED','STARTED','RUNNING','FINISHED','STOPPED','ERROR'))),
        config jsonb,
        output_data jsonb,
        primary key (id)
    );

    create table files (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        lo_oid bigint,
        size bigint,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        secret varchar(32),
        contentType varchar(255),
        fileName varchar(255),
        keycloak_id varchar(255) not null,
        primary key (id)
    );

    create table model_accesses (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        model_id bigint not null,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        access varchar(255) check ((access in ('CREATED','READ','USE','DOWNLOAD','PARTICIPANT'))),
        group_name varchar(255),
        keycloak_id varchar(255) not null,
        primary key (id)
    );

    create table model_sub_files (
        created_at timestamp(6) not null,
        file_id bigint unique,
        id bigint generated by default as identity,
        model_sub_id bigint not null,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        primary key (id)
    );

    create table model_subs (
        created_at timestamp(6) not null,
        experiment_run_id bigint unique,
        federated_experiment_id bigint,
        id bigint generated by default as identity,
        model_version_id bigint not null,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        publish_hash varchar(100) unique,
        image_name varchar(255),
        model_name varchar(255),
        model_path varchar(255),
        status varchar(255) check ((status in ('INITIALIZED','TRAINING','TRAINED'))),
        publish_info json,
        primary key (id)
    );

    create table model_versions (
        created_at timestamp(6) not null,
        experiment_id bigint,
        federated_experiment_id bigint,
        id bigint generated by default as identity,
        major_version bigint,
        minor_version bigint,
        model_id bigint not null,
        patch_version bigint,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        publish_status varchar(50) check ((publish_status in ('PUBLISHED','PRIVATE','RESTRICTED'))),
        changelog varchar(255),
        primary key (id)
    );

    create table models (
        created_at timestamp(6) not null,
        federated_app_version_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        unique_model_id uuid not null unique,
        short_description varchar(500),
        long_description varchar(20000),
        name varchar(255),
        publish_status varchar(255) check ((publish_status in ('PUBLISHED','PRIVATE','RESTRICTED'))),
        primary key (id)
    );

    create table notifications (
        deliveryAttemptCount integer,
        archivedAt timestamp(6),
        created_at timestamp(6) not null,
        deliveredAt timestamp(6),
        deliveredFailedAt timestamp(6),
        id bigint generated by default as identity,
        readAt timestamp(6),
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        message varchar(4000) not null,
        actionUrl varchar(255),
        deliveryErrorMessage varchar(255),
        priority varchar(255) not null check ((priority in ('LOW','NORMAL','HIGH','CRITICAL'))),
        recipientUserId varchar(255) not null,
        sourceEntityId varchar(255),
        sourceEntityType varchar(255),
        sourceService varchar(255),
        status varchar(255) not null check ((status in ('PENDING','DELIVERED','FAILED','READ','ARCHIVED'))),
        title varchar(255) not null,
        type varchar(255) not null check ((type in ('INFO','SUCCESS','WARNING','ERROR','ACTION_REQUIRED'))),
        primary key (id)
    );

    create table pipeline (
        app_version_id bigint,
        created_at timestamp(6) not null,
        docker_tag varchar(8),
        id bigint generated by default as identity,
        model_sub_id bigint,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        container_id varchar(255),
        pipeline_status varchar(255) check ((pipeline_status in ('PENDING','RUNNING','SUCCESS','WARNING','STOPPED','FAILED'))),
        pipeline_type varchar(255) check ((pipeline_type in ('MODEL','APP'))),
        secret varchar(255),
        publish_info json,
        primary key (id)
    );

    create table pipeline_steps (
        progress integer,
        created_at timestamp(6) not null,
        finished_at timestamp(6),
        id bigint generated by default as identity,
        pipeline_id bigint not null,
        started_at timestamp(6),
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        error_code varchar(255),
        error_message TEXT,
        logs TEXT,
        name varchar(255) not null check ((name in ('PREFLIGHT','CLONE_REPO','BUILD_IMAGE','FETCH_CONFIG','FETCH_FILES','PUSH_IMAGE','SCAN_IMAGE','MALWARE_CHECK','RUN_PYTEST','COLLECT_SUMMARY'))),
        stepStatus varchar(255) not null check ((stepStatus in ('PENDING','RUNNING','SUCCESS','WARNING','STOPPED','FAILED'))),
        primary key (id)
    );

    create table project_federated_experiments (
        clinic_is_coordinator boolean default false,
        model_can_be_public boolean default true,
        model_need_to_be_public boolean default false,
        acceptance_clinic_count bigint,
        acceptance_count bigint,
        coordinator_id bigint unique,
        created_at timestamp(6) not null,
        current_step_id bigint,
        finished_at timestamp(6),
        id bigint generated by default as identity,
        project_id bigint not null,
        started_at timestamp(6),
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        workflow_id bigint,
        channel_id varchar(64),
        description varchar(255),
        diagram_config TEXT,
        experiment_status varchar(255) check ((experiment_status in ('INIT','READY','PREPARE','RUNNING','SHUTDOWN','STOPPED','ERROR','FINISHED'))),
        global_unique_id varchar(255) not null unique,
        name varchar(255),
        project_version TEXT,
        relay_server_address varchar(255),
        primary key (id)
    );

    create table project_federated_experiments_participants (
        is_coordinator boolean default false,
        model_can_be_public boolean default false,
        created_at timestamp(6) not null,
        experiment_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        current_node_id varchar(255),
        project_status varchar(255) check ((project_status in ('PENDING','INITIALIZED','STARTED','RUNNING','FINISHED','STOPPED','ERROR'))),
        step_status varchar(255) check ((step_status in ('INIT','READY','PREPARE','RUNNING','SHUTDOWN','STOPPED','ERROR','FINISHED'))),
        unique_random_clinic_id varchar(255),
        primary key (id),
        unique (experiment_id, unique_random_clinic_id)
    );

    create table project_federated_experiments_run_metrics (
        created_at timestamp(6) not null,
        experiment_step_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        message TEXT,
        primary key (id)
    );

    create table project_federated_experiments_steps (
        progress float4,
        created_at timestamp(6) not null,
        experiment_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        workflow_node_id bigint not null,
        last_error varchar(2000),
        channel_id TEXT,
        container_id varchar(255),
        relay_key TEXT,
        step_status varchar(255) check ((step_status in ('PENDING','INITIALIZED','STARTED','RUNNING','FINISHED','STOPPED','ERROR'))),
        meta jsonb,
        primary key (id)
    );

    create table project_local_experiments (
        is_test_run boolean,
        created_at timestamp(6) not null,
        current_step_id bigint,
        finished_at timestamp(6),
        id bigint generated by default as identity,
        project_id bigint not null,
        started_at timestamp(6),
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        description varchar(255),
        diagram_config TEXT,
        experiment_status varchar(255) check ((experiment_status in ('INIT','READY','PREPARE','RUNNING','SHUTDOWN','STOPPED','ERROR','FINISHED'))),
        groupId varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table project_local_experiments_step_messages (
        created_at timestamp(6) not null,
        experiment_step_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        message TEXT,
        process varchar(255),
        type varchar(255) check ((type in ('METRIC','LOG'))),
        primary key (id)
    );

    create table project_local_experiments_step_results (
        created_at timestamp(6) not null,
        file_id bigint,
        id bigint generated by default as identity,
        step_input_id bigint,
        step_output_id bigint,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        name varchar(255),
        result TEXT,
        primary key (id)
    );

    create table project_local_experiments_steps (
        progress float4,
        created_at timestamp(6) not null,
        experiment_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        workflow_node_id bigint not null,
        last_error varchar(2000),
        container_id varchar(255),
        step_status varchar(255) check ((step_status in ('PENDING','INITIALIZED','STARTED','RUNNING','FINISHED','STOPPED','ERROR'))),
        meta jsonb,
        primary key (id)
    );

    create table project_memberships (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        project_id bigint not null,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        keycloak_id varchar(255) not null,
        primary key (id),
        unique (project_id, keycloak_id)
    );

    create table projects (
        certificationLevel integer default 0 not null,
        coordinator_has_data boolean default true,
        isAudited boolean default false not null,
        platform_is_coordinator boolean default false,
        created_at timestamp(6) not null,
        file_id bigint,
        id bigint generated by default as identity,
        query_id bigint,
        updated_at timestamp(6) not null,
        verified_on timestamp(6),
        version bigint default 0 not null,
        workflow_id bigint,
        description varchar(1000),
        name varchar(255),
        export_config json,
        primary key (id)
    );

    create table queries (
        has_fired boolean default false,
        has_result boolean default false,
        result integer,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        latest_data_statistics_request_timestamp timestamp(6),
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        latest_data_statistics_request uuid,
        description varchar(255),
        error TEXT,
        global_unique_id varchar(255) not null unique,
        group_id varchar(255) not null,
        keycloak_id varchar(255) not null,
        name varchar(255),
        query_string TEXT,
        primary key (id)
    );

    create table query_result (
        count integer,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        query_id bigint not null,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        error varchar(255),
        primary key (id)
    );

    create table run_metrics_request (
        created_at timestamp(6) not null,
        experiment_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        global_request_id uuid not null unique,
        request_keycloak_id varchar(255) not null,
        primary key (id)
    );

    create table run_metrics_response (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        metrics_request_id bigint not null,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        random_clinic_id varchar(255) not null,
        metrics jsonb,
        primary key (id)
    );

    create table store_ratings (
        rating float4 default 0 not null,
        app_id bigint,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        model_version_id bigint,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        review_text varchar(1024),
        keycloak_id varchar(255) not null,
        primary key (id)
    );

    create table test_run_messages (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        test_run_id bigint not null,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        message TEXT,
        process varchar(255),
        type varchar(255) check ((type in ('METRIC','LOG'))),
        primary key (id)
    );

    create table test_runs (
        created_at timestamp(6) not null,
        federated_app_version_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        error TEXT,
        hyperParams TEXT,
        input TEXT,
        input_file_path varchar(255),
        output TEXT,
        status varchar(255) check ((status in ('PENDING','INITIALIZED','STARTED','RUNNING','FINISHED','STOPPED','ERROR'))),
        meta jsonb,
        primary key (id)
    );

    create table tool_audit (
        app_version_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        decision varchar(255) check ((decision in ('ACCEPT','REJECT'))),
        keycloak_id varchar(255) not null,
        reason TEXT,
        primary key (id)
    );

    create table workflow (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        publish_status varchar(50) check ((publish_status in ('PUBLISHED','UNPUBLISHED'))),
        description varchar(2000),
        keycloak_id varchar(255) not null,
        name varchar(255),
        export_config json,
        primary key (id)
    );

    create table workflow_connections (
        is_input_connection BOOLEAN DEFAULT FALSE not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        input_config_id bigint not null,
        input_node_id bigint not null,
        output_config_id bigint,
        output_node_id bigint,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        workflow_id bigint not null,
        input_id varchar(255) not null,
        output_id varchar(255) not null,
        primary key (id)
    );

    create table workflow_node (
        execution_order integer,
        app_version_id bigint,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        sub_model_id bigint,
        updated_at timestamp(6) not null,
        version bigint default 0 not null,
        workflow_id bigint not null,
        hyperParams TEXT,
        node_id varchar(255),
        position TEXT,
        primary key (id)
    );

    alter table if exists data_analysis_chat_human_in_the_loop_request 
       add constraint FKeqn6s04q6r79o579a2qhkafx9 
       foreign key (message_id) 
       references data_analysis_chat_message;

    alter table if exists data_analysis_chat_message 
       add constraint FKpxr8lo52kv0dpomd5r8t3difc 
       foreign key (workflow_id) 
       references data_analysis;

    alter table if exists data_analysis_files 
       add constraint FK4exl652pgyq7x8uro2v07oppf 
       foreign key (data_analysis_id) 
       references data_analysis;

    alter table if exists data_analysis_files 
       add constraint FKr6ten1q8kstf3ud7r7si61i9l 
       foreign key (file_id) 
       references files 
       on delete cascade;

    alter table if exists data_analysis_files 
       add constraint FKn49odm23bve50nxdlwna78xx1 
       foreign key (prediction_id) 
       references data_analysis_predictions 
       on delete cascade;

    alter table if exists data_analysis_files 
       add constraint FKjtp21xmhqbpd02ryvrgv62g9i 
       foreign key (workflow_step_id) 
       references data_analysis_workflow_run_steps 
       on delete cascade;

    alter table if exists data_analysis_predictions 
       add constraint FK6st2gsp2ew387qto0j2bq14kk 
       foreign key (data_analysis_id) 
       references data_analysis;

    alter table if exists data_analysis_predictions 
       add constraint FK6budiy1kssk0ycqm5ajy9erjg 
       foreign key (app_version_id) 
       references federated_app_versions;

    alter table if exists data_analysis_predictions 
       add constraint FKmb3qw9r3rfxx2vbc3p0yfolfe 
       foreign key (sub_model_id) 
       references model_subs;

    alter table if exists data_analysis_workflow_run_step_messages 
       add constraint FKtlrjr9aa8nq4snwknr64oo8xu 
       foreign key (prediction_id) 
       references data_analysis_predictions 
       on delete cascade;

    alter table if exists data_analysis_workflow_run_step_messages 
       add constraint FKiuawqs53vjibbleromjl0xury 
       foreign key (experiment_step_id) 
       references data_analysis_workflow_run_steps 
       on delete cascade;

    alter table if exists data_analysis_workflow_run_steps 
       add constraint FK1166dy5494pmkfpxq1vdrwmkm 
       foreign key (experiment_id) 
       references data_analysis_workflow_runs 
       on delete cascade;

    alter table if exists data_analysis_workflow_run_steps 
       add constraint FKlelic5fes4guoiiqxufp91m5d 
       foreign key (workflow_node_id) 
       references workflow_node;

    alter table if exists data_analysis_workflow_runs 
       add constraint FKigudjswekuudbxyd0jk0dvqkw 
       foreign key (current_step_id) 
       references data_analysis_workflow_run_steps;

    alter table if exists data_analysis_workflow_runs 
       add constraint FKaa9ddpy7fechhloou22s9aoxk 
       foreign key (data_analysis_id) 
       references data_analysis;

    alter table if exists data_analysis_workflow_runs 
       add constraint FKb8gycso5w9mrhw15pcexw9cbq 
       foreign key (workflow_id) 
       references workflow;

    alter table if exists data_statistics_result 
       add constraint FKfx4hgyb0jsesrflxniw73bcv6 
       foreign key (query_id) 
       references queries;

    alter table if exists experiments 
       add constraint FK8v47lyov8s1fwq2kmst07gq5 
       foreign key (federated_app_version_id) 
       references federated_app_versions;

    alter table if exists experiments_run_messages 
       add constraint FK1msia94o2en8yjhf54xt6ieg8 
       foreign key (experiment_run_id) 
       references experiments_runs;

    alter table if exists experiments_runs 
       add constraint FKkqgl9r2v70btrxcurwrj1ae2u 
       foreign key (experiment_id) 
       references experiments;

    alter table if exists federated_app_authors 
       add constraint FKcqjsk671rb7sb9sj7rqbgdq5j 
       foreign key (federated_app_id) 
       references federated_apps;

    alter table if exists federated_app_hyperparam_configs 
       add constraint FKeg571ji44gtkpvoaqx3ho1tm7 
       foreign key (federated_app_version_id) 
       references federated_app_versions;

    alter table if exists federated_app_input_configs 
       add constraint FKojc8npqmcrykomu5i0tk0021a 
       foreign key (federated_app_version_id) 
       references federated_app_versions;

    alter table if exists federated_app_output_configs 
       add constraint FKojjrrbd87pjgpbit8ui4m5701 
       foreign key (federated_app_version_id) 
       references federated_app_versions;

    alter table if exists federated_app_versions 
       add constraint FK7kjjtmerwm4p54h9dn9yxw6vi 
       foreign key (federated_app_id) 
       references federated_apps;

    alter table if exists federated_apps_tags 
       add constraint FKr552x0bigcdecqov6gw9xyvqh 
       foreign key (federated_app_id) 
       references federated_app_tags;

    alter table if exists federated_apps_tags 
       add constraint FKq9u0gsx74ltfhjggfcbn5jeie 
       foreign key (federated_tag_id) 
       references federated_apps;

    alter table if exists federated_participant_messages 
       add constraint FKone5hvslxryqratu0ge4e39ua 
       foreign key (participant_id) 
       references federated_run_participants;

    alter table if exists federated_round_messages 
       add constraint FKougncrbuscaiahr7d0b8pomqp 
       foreign key (federated_run_id) 
       references federated_test_runs;

    alter table if exists federated_run_participants 
       add constraint FKt65ryd3r31upj1a25q4wy6a7y 
       foreign key (federated_run_id) 
       references federated_test_runs;

    alter table if exists federated_test_runs 
       add constraint FKv4184jl4b2krqkts2ltaveer 
       foreign key (federated_app_version_id) 
       references federated_app_versions;

    alter table if exists model_accesses 
       add constraint FK9rdtg4p2iqe9533008eidabfo 
       foreign key (model_id) 
       references models;

    alter table if exists model_sub_files 
       add constraint FKqmurp6b20ir62ojmnci7ij6ky 
       foreign key (file_id) 
       references files 
       on delete cascade;

    alter table if exists model_sub_files 
       add constraint FK6n6570iapiq1oxdcykcvv3sa 
       foreign key (model_sub_id) 
       references model_subs;

    alter table if exists model_subs 
       add constraint FKi3538y5fl9f5sn66grl5lvtgv 
       foreign key (experiment_run_id) 
       references experiments_runs;

    alter table if exists model_subs 
       add constraint FKdsln2tmd256oi12lmdlwx5y0u 
       foreign key (federated_experiment_id) 
       references project_federated_experiments;

    alter table if exists model_subs 
       add constraint FKmvrbdpvuvbf601ior3fm4266n 
       foreign key (model_version_id) 
       references model_versions;

    alter table if exists model_versions 
       add constraint FKsaneeiunlr0wq0eff4g6iqhd 
       foreign key (experiment_id) 
       references experiments;

    alter table if exists model_versions 
       add constraint FKc0pxapy66b0rynwmi4rb2g8nk 
       foreign key (federated_experiment_id) 
       references project_federated_experiments;

    alter table if exists model_versions 
       add constraint FKohjmv1ksq0dayiew04yp3m0ab 
       foreign key (model_id) 
       references models;

    alter table if exists models 
       add constraint FK1qbanved9o0glu9v1mo32duyb 
       foreign key (federated_app_version_id) 
       references federated_app_versions;

    alter table if exists pipeline 
       add constraint FK6njcncc4fcw87rv1sw5seb6dp 
       foreign key (app_version_id) 
       references federated_app_versions;

    alter table if exists pipeline 
       add constraint FK3ndovvwi7y6q0vspxnj477i1w 
       foreign key (model_sub_id) 
       references model_subs;

    alter table if exists pipeline_steps 
       add constraint FKr55kqxbipf4t68616367n10h8 
       foreign key (pipeline_id) 
       references pipeline;

    alter table if exists project_federated_experiments 
       add constraint FKchwcph3789tur4swjai95jyrd 
       foreign key (current_step_id) 
       references project_federated_experiments_steps;

    alter table if exists project_federated_experiments 
       add constraint FKoywncrvhcvygk86ofve1jn45y 
       foreign key (coordinator_id) 
       references project_federated_experiments_participants;

    alter table if exists project_federated_experiments 
       add constraint FK27ufydjqo8hsjuemje6v158kb 
       foreign key (project_id) 
       references projects;

    alter table if exists project_federated_experiments 
       add constraint FKforlmea3kujhdppfdoin2nei0 
       foreign key (workflow_id) 
       references workflow;

    alter table if exists project_federated_experiments_participants 
       add constraint FKldmi4ecw7lwl5if2s5acjf4d9 
       foreign key (experiment_id) 
       references project_federated_experiments;

    alter table if exists project_federated_experiments_run_metrics 
       add constraint FK2mjf2nlcwggicvoydonwu28jy 
       foreign key (experiment_step_id) 
       references project_federated_experiments_steps;

    alter table if exists project_federated_experiments_steps 
       add constraint FKj6aqgiaw3o8w6gg183rvm9cna 
       foreign key (experiment_id) 
       references project_federated_experiments 
       on delete cascade;

    alter table if exists project_federated_experiments_steps 
       add constraint FKlhhakq0u9xg8gvg73qlx8yxq4 
       foreign key (workflow_node_id) 
       references workflow_node;

    alter table if exists project_local_experiments 
       add constraint FKiete81gn1dfj1lq3evhq619ma 
       foreign key (current_step_id) 
       references project_local_experiments_steps;

    alter table if exists project_local_experiments 
       add constraint FK4f772ptbb2s6572m2exh05hcg 
       foreign key (project_id) 
       references projects;

    alter table if exists project_local_experiments_step_messages 
       add constraint FK4g91v8kp7ll287eulisp5yanq 
       foreign key (experiment_step_id) 
       references project_local_experiments_steps 
       on delete cascade;

    alter table if exists project_local_experiments_step_results 
       add constraint FKauo3xv6sa64sreph9w131sede 
       foreign key (file_id) 
       references files;

    alter table if exists project_local_experiments_step_results 
       add constraint FKa212jwdcyanrq3hfkrc61qyqd 
       foreign key (step_input_id) 
       references project_local_experiments_steps;

    alter table if exists project_local_experiments_step_results 
       add constraint FKkbyyf9xcmu5pqntwmcfhga3i3 
       foreign key (step_output_id) 
       references project_local_experiments_steps;

    alter table if exists project_local_experiments_steps 
       add constraint FKfsvk2k2r9yswfg5k0bhexowhq 
       foreign key (experiment_id) 
       references project_local_experiments 
       on delete cascade;

    alter table if exists project_local_experiments_steps 
       add constraint FKfqdx6t3qt5vn0ut3unbiu9ns7 
       foreign key (workflow_node_id) 
       references workflow_node;

    alter table if exists project_memberships 
       add constraint FKd90uwkxsbfhownoqpuw443iqf 
       foreign key (project_id) 
       references projects;

    alter table if exists projects 
       add constraint FK1184khw9qb5h0a9ui1bthhlm 
       foreign key (file_id) 
       references files 
       on delete cascade;

    alter table if exists projects 
       add constraint FKcntrvuv9kxyrnsuk8yio1dt7r 
       foreign key (query_id) 
       references queries;

    alter table if exists projects 
       add constraint FK9ou7r1q91x0jw8ulkcdl4pqar 
       foreign key (workflow_id) 
       references workflow;

    alter table if exists query_result 
       add constraint FKjxfax0vantuytpwls1fiff8a6 
       foreign key (query_id) 
       references queries;

    alter table if exists run_metrics_request 
       add constraint FKnsr6rutb0rnc566as4m16gawv 
       foreign key (experiment_id) 
       references project_federated_experiments;

    alter table if exists run_metrics_response 
       add constraint FKf9dcjiiud12yyeqjxpf4lrre1 
       foreign key (metrics_request_id) 
       references run_metrics_request 
       on delete cascade;

    alter table if exists store_ratings 
       add constraint FK8dagxfs8n5no09wndlegob6i8 
       foreign key (app_id) 
       references federated_apps;

    alter table if exists store_ratings 
       add constraint FK3xlrvxensoq58k5j12k03pe4b 
       foreign key (model_version_id) 
       references model_versions;

    alter table if exists test_run_messages 
       add constraint FKg92c2cnwar2000uhlpsu5ln73 
       foreign key (test_run_id) 
       references test_runs;

    alter table if exists test_runs 
       add constraint FKbp3arl9wwkud22omj1n0tduj9 
       foreign key (federated_app_version_id) 
       references federated_app_versions;

    alter table if exists tool_audit 
       add constraint FKju9s6vcb54mh7cwslh83k0dfp 
       foreign key (app_version_id) 
       references federated_app_versions;

    alter table if exists workflow_connections 
       add constraint FKqbs08spt5u8cymjdfpm96sxbk 
       foreign key (input_config_id) 
       references federated_app_input_configs;

    alter table if exists workflow_connections 
       add constraint FKh7b9k39pyciip00x9iffhc96o 
       foreign key (input_node_id) 
       references workflow_node 
       on delete cascade;

    alter table if exists workflow_connections 
       add constraint FKcpwx22f0mhxfssp8aacl5xyiq 
       foreign key (output_config_id) 
       references federated_app_output_configs;

    alter table if exists workflow_connections 
       add constraint FK1chtq01ga3wsfmbwe8onsvdey 
       foreign key (output_node_id) 
       references workflow_node 
       on delete cascade;

    alter table if exists workflow_connections 
       add constraint FK6epvfncscs6utns3dgdrphjxm 
       foreign key (workflow_id) 
       references workflow 
       on delete cascade;

    alter table if exists workflow_node 
       add constraint FKmc9a3f04hnuoobxq9yeidsebo 
       foreign key (app_version_id) 
       references federated_app_versions;

    alter table if exists workflow_node 
       add constraint FKal5x2lo3deh5ol0a1x8d61nap 
       foreign key (sub_model_id) 
       references model_subs;

    alter table if exists workflow_node 
       add constraint FKko4nyv15u7ixp39g9ah8tcpb8 
       foreign key (workflow_id) 
       references workflow 
       on delete cascade;
CREATE EXTENSION IF NOT EXISTS vector;